#!/bin/sh

LOCAL="$1"
NAME="$2"

if [ -z "$LOCAL" ] || [ -z "$NAME" ]; then
    echo "send-to-prod <directory> <name>"
    exit
fi

HOST="scaleway"
REMOTE="Coding/$NAME"

rsync -avzhP . "$HOST:$REMOTE" --exclude-from=- --delete <<EOF
*.sqlite
__pycache__
target/
EOF

ssh "$HOST" <<EOF
cd "$HOME/$REMOTE"

tmux kill-session -t "$NAME"

if [ -f Cargo.toml ]; then
    tmux new -d -s "$NAME" 'nix-shell --run "cargo run --release; zsh"'
elif [ -f main.py ]; then
    tmux new -d -s "$NAME" 'source ../activate.sh && pip install -Ur requirements.txt && python main.py; zsh'
fi
EOF

echo "Updated!"
